package com.vinsys.hrms.kra.util;

public enum EKraStatus {
	INCOMPLETE, INPROCESS, APPROVED, REJECTED, INVALID_INPUT, MANAGER,PENDING,SUBMITTED,COMPLETED,EMPLOYEE, INPROGRESS, INACTION, CALIBRATING, CORRECTION
	
}
