package com.vinsys.hrms.util;

public enum EChecklistItems {
	PROFILE_DETAILS,ADDRESS_DETAILS,EDUCATIONAL_DETAILS,CERTIFICATION_DETAILS,HEALTH_DETAILS,FAMILY_DETAILS,PREVIOUS_EMPLOYMENT_DETAILS,BANK_DETAILS,CURRENT_DETAILS
}
