package com.vinsys.hrms.util;

public enum ERole {
	ORG_ADMIN, CANDIDATE, MANAGER, EMPLOYEE, HR, Recruiter,OFFICE_ADMIN,TRAVEL_DESK,TRAVEL_DESK_APPROVER,ACCOUNTANT,HOD,PERFORMANCE_MANAGER, DELEGATOR, ADMIN,DIVISIONHEAD, TDHEAD
}
